// Pre-generated exercise content for fast loading
// This content is generated by Gemini AI and cached for performance

export interface ExerciseContent {
  instruction: string;
  tips?: string[];
  encouragement?: string;
}

// Pre-generated Stress Buster content (5 variations per technique)
export const STRESS_BUSTER_CONTENT: Record<string, ExerciseContent[]> = {
  '5-4-3-2-1 Grounding': [
    {
      instruction: 'Notice 5 things you can see around you. Name 4 objects you can touch. Listen for 3 sounds. Identify 2 scents. Focus on 1 taste. This grounds you in the present moment.',
      tips: ['Be specific with your observations', 'Take your time with each sense', 'No judgment, just notice'],
      encouragement: 'You\'re bringing yourself back to the present. That\'s powerful.'
    },
    {
      instruction: 'Start by looking around and naming 5 visible objects. Touch 4 different textures nearby. Listen carefully for 3 distinct sounds. Notice 2 smells in your environment. Finally, focus on 1 taste in your mouth.',
      tips: ['Go slowly through each step', 'Use all your senses fully', 'Stay curious, not critical'],
      encouragement: 'Grounding yourself helps calm your nervous system. Keep going.'
    },
    {
      instruction: 'Use your senses to anchor yourself: See 5 things, touch 4 items, hear 3 sounds, smell 2 scents, taste 1 thing. This technique interrupts anxious thoughts by focusing on your environment.',
      tips: ['Be present with each sense', 'Don\'t rush the process', 'This is a proven grounding technique'],
      encouragement: 'You\'re doing great. Each sense brings you closer to calm.'
    },
    {
      instruction: 'Ground yourself by engaging all senses. Look for 5 things you see. Feel 4 different textures. Listen for 3 sounds. Notice 2 smells. Focus on 1 taste. This brings your mind to the here and now.',
      tips: ['Take deep breaths between steps', 'Be gentle with yourself', 'This works by redirecting focus'],
      encouragement: 'You\'re taking control by grounding yourself. That\'s strength.'
    },
    {
      instruction: 'Practice the 5-4-3-2-1 method: Observe 5 visual items, touch 4 objects, identify 3 sounds, notice 2 scents, focus on 1 taste. This sensory exercise helps reduce stress and anxiety.',
      tips: ['Work through each number methodically', 'Engage fully with each sense', 'This technique is scientifically proven'],
      encouragement: 'You\'re actively managing your stress. That\'s progress.'
    }
  ],
  'Progressive Muscle Relaxation': [
    {
      instruction: 'Tense each muscle group for 5 seconds, then release completely. Start with your toes, move to calves, thighs, abdomen, hands, arms, shoulders, and face. Notice the contrast between tension and relaxation.',
      tips: ['Hold tension firmly but not painfully', 'Release slowly and completely', 'Focus on the feeling of relaxation'],
      encouragement: 'Your body is learning to release tension. That\'s healing.'
    },
    {
      instruction: 'Systematically tense and release muscle groups from toes to head. Tense for 5 seconds, then let go. Feel the wave of relaxation spread through your body as you progress upward.',
      tips: ['Move slowly through each area', 'Breathe deeply during release', 'Notice how relaxation feels'],
      encouragement: 'You\'re teaching your body to relax. Keep practicing.'
    },
    {
      instruction: 'Begin with your feet: tense for 5 seconds, release. Move up your body - legs, stomach, hands, arms, shoulders, face. Each release brings deeper relaxation. This technique reduces physical stress.',
      tips: ['Don\'t skip any muscle groups', 'Feel the difference between tense and relaxed', 'Breathe naturally throughout'],
      encouragement: 'Your body is responding to your care. That\'s beautiful.'
    },
    {
      instruction: 'Progressive relaxation: tense each body part for 5 seconds, then release. Work from bottom to top - feet, legs, core, arms, shoulders, face. The release phase is where healing happens.',
      tips: ['Tense enough to feel it, not to strain', 'Release is more important than tension', 'Practice makes this more effective'],
      encouragement: 'You\'re actively reducing physical stress. That\'s self-care.'
    },
    {
      instruction: 'Tense muscles progressively from toes to head, holding each for 5 seconds before releasing. This technique teaches your body the difference between tension and relaxation, helping you manage stress.',
      tips: ['Go in order: bottom to top', 'Focus on the release sensation', 'This is a proven stress reduction method'],
      encouragement: 'You\'re learning to control your body\'s response. That\'s empowerment.'
    }
  ],
  'Box Breathing': [
    {
      instruction: 'Inhale for 4 counts, hold for 4, exhale for 4, hold for 4. Repeat this box pattern. This breathing technique activates your parasympathetic nervous system, promoting calm.',
      tips: ['Count slowly and evenly', 'Keep the rhythm consistent', 'Focus on the breath, not thoughts'],
      encouragement: 'Your breath is a powerful tool for calm. Use it well.'
    },
    {
      instruction: 'Practice box breathing: 4 counts in, 4 hold, 4 out, 4 hold. This equal-length pattern creates balance in your nervous system. Repeat for several cycles to feel the calming effect.',
      tips: ['Maintain equal timing for each phase', 'Breathe through your nose', 'Let your body relax into the rhythm'],
      encouragement: 'You\'re regulating your nervous system. That\'s skill.'
    },
    {
      instruction: 'Box breathing uses equal counts: inhale 4, hold 4, exhale 4, hold 4. This technique calms your mind and body by balancing your breathing pattern. Continue for several rounds.',
      tips: ['Start with 4 counts, adjust if needed', 'The hold phases are important', 'This works by resetting your nervous system'],
      encouragement: 'You\'re creating calm through your breath. That\'s powerful.'
    },
    {
      instruction: 'Follow the box pattern: 4-4-4-4 breathing. Inhale 4, hold 4, exhale 4, hold 4. This structured breathing activates relaxation responses in your body. Repeat to deepen the effect.',
      tips: ['Keep counts equal and steady', 'Don\'t force the breath', 'This technique is used by professionals'],
      encouragement: 'Your breath is bringing you peace. That\'s transformation.'
    },
    {
      instruction: 'Box breathing: 4 counts each phase. Inhale (4), hold (4), exhale (4), hold (4). This equal-ratio breathing pattern helps regulate stress and anxiety by calming your nervous system.',
      tips: ['Consistency is key', 'Focus on smooth transitions', 'This is a proven relaxation technique'],
      encouragement: 'You\'re mastering your breath. That\'s control.'
    }
  ]
};

// Pre-generated Sleep Stories content (5 variations per story)
export const SLEEP_STORIES_CONTENT: Record<string, string[][]> = {
  'The Peaceful Forest': [
    [
      'You find yourself at the edge of a peaceful forest, where ancient trees stand tall and gentle.',
      'A soft breeze rustles through the leaves, creating a soothing whisper that calms your mind.',
      'Sunlight filters through the canopy in golden streams, warming your skin gently.',
      'A small stream flows nearby, its gentle babbling creating a natural lullaby.',
      'You walk deeper into the forest, feeling the soft moss beneath your feet.',
      'The air is fresh and clean, filled with the scent of pine and earth.',
      'Birds sing softly in the distance, their melodies blending into harmony.',
      'You find a comfortable spot beneath a large tree and settle in, feeling completely at peace.',
      'Your body begins to relax completely, releasing all tension and worry.',
      'As you close your eyes, you drift into a deep, restful sleep.'
    ],
    [
      'Imagine stepping into a serene forest where time seems to slow down.',
      'Tall trees surround you, their branches swaying gently in the breeze.',
      'The forest floor is carpeted with soft moss and fallen leaves.',
      'You hear the distant sound of water, a stream flowing peacefully.',
      'Dappled sunlight creates patterns on the ground, moving slowly.',
      'The temperature is perfect - neither too warm nor too cool.',
      'You take a deep breath, inhaling the fresh, clean forest air.',
      'Every step feels lighter as you walk deeper into tranquility.',
      'Your mind becomes quiet, thoughts floating away like leaves.',
      'You feel safe, protected, and ready for deep rest.'
    ],
    [
      'You enter a magical forest where peace flows like a river.',
      'Ancient trees create a natural cathedral overhead, filtering the light.',
      'The ground is soft and welcoming, inviting you to rest.',
      'Nature sounds surround you - rustling leaves, chirping birds, flowing water.',
      'Each breath brings you deeper into relaxation and calm.',
      'The forest seems to embrace you, offering comfort and safety.',
      'Worries fade away, replaced by a sense of profound peace.',
      'Your body feels heavy and relaxed, sinking into the earth.',
      'The gentle sounds become a lullaby, guiding you toward sleep.',
      'You surrender completely to rest, feeling completely secure.'
    ],
    [
      'A peaceful forest path opens before you, inviting you to explore.',
      'The trees are old and wise, standing as guardians of tranquility.',
      'Soft light filters through green leaves, creating a dreamy atmosphere.',
      'You hear the gentle sound of a nearby stream, constant and soothing.',
      'The forest floor is soft and springy, perfect for walking barefoot.',
      'Cool, fresh air fills your lungs with each deep breath.',
      'You feel connected to nature, part of something larger and peaceful.',
      'Time seems to stand still in this sacred space.',
      'Your body relaxes completely, muscles releasing all tension.',
      'Sleep comes naturally, like a gentle wave washing over you.'
    ],
    [
      'You discover a hidden forest glade, a perfect circle of peace.',
      'Tall trees form a natural shelter, protecting you from the world.',
      'Sunlight dances through leaves, creating a calming, hypnotic pattern.',
      'The sound of water nearby creates a steady, rhythmic background.',
      'Everything here feels safe, soft, and designed for rest.',
      'You lie down on the soft ground, feeling completely supported.',
      'The forest sounds blend into a single, soothing melody.',
      'Your breathing slows naturally, matching the rhythm of nature.',
      'Thoughts drift away, leaving only peace and stillness.',
      'You slip into sleep as easily as a leaf falls from a tree.'
    ]
  ],
  'Ocean Waves': [
    [
      'You find yourself on a warm, sandy beach as the sun sets gently.',
      'Ocean waves roll in and out with a steady, rhythmic motion.',
      'Each wave brings a sense of peace, washing away your worries.',
      'The sand beneath you is warm and soft, perfectly comfortable.',
      'A gentle sea breeze cools your skin, feeling refreshing and calm.',
      'The sound of waves is constant and soothing, like nature\'s heartbeat.',
      'You watch the horizon where sky meets ocean in perfect harmony.',
      'The rhythm of the waves matches your breathing, slowing it down.',
      'Your body feels heavy and relaxed, like you\'re floating.',
      'You drift into sleep to the lullaby of the ocean.'
    ],
    [
      'Imagine lying on a beautiful beach as evening approaches.',
      'The ocean stretches before you, vast and peaceful.',
      'Waves crash gently on the shore, creating a rhythmic sound.',
      'Warm sand cradles your body, supporting you completely.',
      'The air is salty and fresh, filling your lungs with each breath.',
      'Seagulls call in the distance, their cries fading into the background.',
      'The sun paints the sky in soft oranges and pinks.',
      'Each wave that comes in feels like a gentle massage.',
      'Your mind becomes as calm as the ocean on a still day.',
      'Sleep washes over you like a gentle wave.'
    ],
    [
      'You\'re on a secluded beach, completely alone and at peace.',
      'The ocean is calm tonight, waves rolling in slowly and gently.',
      'Stars begin to appear in the darkening sky above.',
      'The sand is still warm from the day\'s sun, comforting you.',
      'You can hear only the ocean - no other sounds disturb the peace.',
      'Each wave brings a feeling of release and letting go.',
      'Your breathing synchronizes with the rhythm of the waves.',
      'The vastness of the ocean makes your worries seem small.',
      'You feel completely safe here, protected by the endless water.',
      'Rest comes naturally, as inevitable as the tide.'
    ],
    [
      'A perfect beach awaits you, untouched and serene.',
      'The ocean waves are gentle tonight, lapping softly at the shore.',
      'Moonlight reflects off the water, creating a silver path.',
      'You settle into the sand, feeling it mold to your body.',
      'The sound of waves is hypnotic, drawing you deeper into relaxation.',
      'Cool ocean air fills your lungs, refreshing and clean.',
      'You watch the waves come and go, each one taking stress away.',
      'Your body feels weightless, floating on the boundary between land and sea.',
      'The constant rhythm of waves lulls your mind into stillness.',
      'Sleep arrives like a gentle tide, covering you in peace.'
    ],
    [
      'You discover a hidden cove where the ocean meets the shore.',
      'Waves roll in with perfect regularity, like a natural metronome.',
      'The beach is pristine, with soft white sand that feels like silk.',
      'Evening light makes everything glow with a warm, golden hue.',
      'The ocean sound is all-encompassing, blocking out everything else.',
      'You lie back and let the sand support your entire body.',
      'Each wave that reaches the shore feels like a gentle caress.',
      'Your mind empties of thoughts, filled only with the ocean\'s rhythm.',
      'The vastness of the sea makes you feel both small and connected.',
      'You surrender to sleep, carried away by the gentle waves.'
    ]
  ]
};

// Pre-generated Anxiety SOS content (5 variations per technique)
export const ANXIETY_SOS_CONTENT: Record<string, ExerciseContent[]> = {
  '4-7-8 Breathing': [
    {
      instruction: 'Inhale through your nose for 4 counts. Hold your breath for 7 counts. Exhale through your mouth for 8 counts. Repeat 4 times. This technique activates your body\'s relaxation response.',
      tips: ['You are safe right now', 'This feeling will pass', 'Your breath is your anchor'],
      encouragement: 'You\'re taking control. This technique works. Keep going.'
    },
    {
      instruction: 'Breathe in for 4, hold for 7, breathe out for 8. This extended exhale calms your nervous system. Repeat the cycle 4 times. Focus only on the counting.',
      tips: ['The long exhale is key', 'You\'re safe in this moment', 'Anxiety is temporary'],
      encouragement: 'You\'re doing exactly what you need. This will help.'
    },
    {
      instruction: '4-7-8 breathing: Inhale (4), hold (7), exhale (8). The longer exhale triggers relaxation. Do 4 complete cycles. Let the counting anchor your mind.',
      tips: ['Count slowly and evenly', 'The exhale calms your system', 'You have the power to calm yourself'],
      encouragement: 'You\'re actively helping yourself. That\'s strength.'
    },
    {
      instruction: 'Practice 4-7-8 breathing: 4 counts in, 7 hold, 8 out. This ratio activates your parasympathetic nervous system, reducing anxiety. Complete 4 rounds.',
      tips: ['Focus on the numbers', 'Your body knows how to calm', 'This is a proven technique'],
      encouragement: 'You\'re managing your anxiety. That\'s powerful.'
    },
    {
      instruction: 'Breathe in 4, hold 7, breathe out 8. Repeat 4 times. The extended exhale signals safety to your body. This technique is used by professionals.',
      tips: ['Trust the process', 'Your body will respond', 'You\'re in control'],
      encouragement: 'You\'re taking care of yourself. That\'s self-compassion.'
    }
  ],
  '5 Senses Check': [
    {
      instruction: 'Ground yourself: Name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste. This brings you back to the present moment, away from anxious thoughts.',
      tips: ['Be specific with each sense', 'This interrupts anxious thinking', 'You\'re safe in the present'],
      encouragement: 'You\'re bringing yourself back to reality. That\'s grounding.'
    },
    {
      instruction: 'Use your senses to anchor yourself: 5 sights, 4 textures, 3 sounds, 2 smells, 1 taste. This technique breaks the cycle of anxious thoughts by focusing on your environment.',
      tips: ['Go slowly through each number', 'Engage fully with each sense', 'The present moment is safe'],
      encouragement: 'You\'re interrupting anxiety. That\'s skill.'
    },
    {
      instruction: 'Practice the 5-4-3-2-1 grounding: Observe 5 visual items, touch 4 objects, identify 3 sounds, notice 2 scents, focus on 1 taste. This technique reduces anxiety by redirecting focus.',
      tips: ['Be present with each sense', 'This works by changing focus', 'You have the tools to calm yourself'],
      encouragement: 'You\'re using proven techniques. That\'s wisdom.'
    },
    {
      instruction: 'Ground yourself with your senses: See 5, touch 4, hear 3, smell 2, taste 1. This sensory exercise pulls your attention away from anxious thoughts and into the present.',
      tips: ['Take your time', 'Be specific with observations', 'The present is where safety lives'],
      encouragement: 'You\'re actively managing anxiety. That\'s empowerment.'
    },
    {
      instruction: 'Engage all senses: 5 things you see, 4 you can touch, 3 sounds, 2 smells, 1 taste. This grounding technique helps reduce anxiety by connecting you to your environment.',
      tips: ['Work through systematically', 'Focus on what\'s real and present', 'You\'re safe right now'],
      encouragement: 'You\'re taking control of your anxiety. That\'s courage.'
    }
  ],
  'Progressive Release': [
    {
      instruction: 'Tense and release each muscle group. Start with toes, work up to head. Tense for 5 seconds, release completely. This physical release helps reduce anxiety in your body.',
      tips: ['The release is more important than tension', 'Your body holds anxiety', 'Release brings relief'],
      encouragement: 'You\'re releasing stored tension. That\'s healing.'
    },
    {
      instruction: 'Systematically tense and release muscles from bottom to top. Hold tension 5 seconds, then let go completely. Feel anxiety leave your body with each release.',
      tips: ['Move slowly through each area', 'Focus on the feeling of release', 'Physical relaxation reduces mental anxiety'],
      encouragement: 'You\'re teaching your body to let go. That\'s progress.'
    },
    {
      instruction: 'Progressive muscle relaxation: Tense each body part for 5 seconds, release. Work from toes to head. This technique reduces physical symptoms of anxiety.',
      tips: ['Don\'t skip any areas', 'The release phase is key', 'Your body responds to this technique'],
      encouragement: 'You\'re actively reducing anxiety. That\'s self-care.'
    },
    {
      instruction: 'Tense muscles progressively, holding each for 5 seconds before releasing. Start with feet, move upward. This physical practice helps calm your nervous system.',
      tips: ['Feel the contrast between tense and relaxed', 'Release is where healing happens', 'This is a proven anxiety technique'],
      encouragement: 'You\'re managing your body\'s response. That\'s control.'
    },
    {
      instruction: 'Practice progressive release: Tense each muscle group 5 seconds, release completely. Work bottom to top. This technique reduces anxiety by releasing physical tension.',
      tips: ['Go in order', 'Focus on complete release', 'Physical calm creates mental calm'],
      encouragement: 'You\'re releasing anxiety from your body. That\'s transformation.'
    }
  ],
  'Safe Place Visualization': [
    {
      instruction: 'Close your eyes and imagine a place where you feel completely safe. Picture every detail - colors, sounds, temperature. Stay in this place for a moment. This visualization calms your nervous system.',
      tips: ['Make it as real as possible', 'You can return here anytime', 'Safety is a feeling you can create'],
      encouragement: 'You\'re creating safety for yourself. That\'s powerful.'
    },
    {
      instruction: 'Visualize a safe, peaceful place. See it clearly - notice colors, textures, sounds. Feel the safety and comfort. This mental sanctuary is always available to you.',
      tips: ['Engage all your senses in the visualization', 'This place is yours alone', 'Visualization is a proven anxiety tool'],
      encouragement: 'You\'re accessing your inner calm. That\'s resourcefulness.'
    },
    {
      instruction: 'Imagine your perfect safe place. Picture it in detail - what you see, hear, feel. Stay there mentally. This visualization technique helps reduce anxiety by creating a mental refuge.',
      tips: ['The more detail, the more effective', 'You control this space', 'This technique works by calming your mind'],
      encouragement: 'You\'re finding peace within. That\'s strength.'
    },
    {
      instruction: 'Create a mental safe place. Visualize it completely - sights, sounds, feelings. Spend time there. This visualization activates your body\'s relaxation response.',
      tips: ['Make it personal and meaningful', 'You can visit anytime', 'Your mind creates real calm'],
      encouragement: 'You\'re building inner resources. That\'s resilience.'
    },
    {
      instruction: 'Picture a place where you feel completely secure. See every detail, hear the sounds, feel the safety. Stay there. This visualization is a powerful anxiety reduction tool.',
      tips: ['Engage all senses in your mind', 'This is your sanctuary', 'Visualization creates real calm'],
      encouragement: 'You\'re accessing your calm center. That\'s wisdom.'
    }
  ]
};

// Pre-generated Mood Booster content (5 variations per activity)
export const MOOD_BOOSTER_CONTENT: Record<string, ExerciseContent[]> = {
  'Gratitude Practice': [
    {
      instruction: 'Think of 3 things you\'re grateful for today. They can be big or small. Write them down or say them out loud. Feel the warmth of appreciation in your heart.',
      tips: ['Be specific about why you\'re grateful', 'Focus on the feeling', 'Gratitude rewires your brain for positivity'],
      encouragement: 'You\'re training your mind to see the good. That\'s powerful.'
    },
    {
      instruction: 'List 3 things you appreciate right now. Notice how each one makes you feel. Gratitude shifts your focus from what\'s wrong to what\'s right.',
      tips: ['Even small things count', 'Feel the emotion of gratitude', 'This practice boosts mood naturally'],
      encouragement: 'You\'re cultivating positivity. That\'s growth.'
    },
    {
      instruction: 'Name 3 things you\'re grateful for. Be specific. Gratitude practice increases happiness and reduces negative emotions. Feel the positive energy.',
      tips: ['Gratitude is a choice', 'The more you practice, the easier it gets', 'This is scientifically proven to boost mood'],
      encouragement: 'You\'re choosing positivity. That\'s empowerment.'
    },
    {
      instruction: 'Think of 3 things that bring you joy or comfort. Express gratitude for each one. This simple practice releases feel-good chemicals in your brain.',
      tips: ['Gratitude doesn\'t deny problems', 'It adds positive perspective', 'Regular practice changes your outlook'],
      encouragement: 'You\'re building a positive mindset. That\'s transformation.'
    },
    {
      instruction: 'Practice gratitude: Identify 3 things you appreciate. Notice the positive feelings that arise. Gratitude is a mood booster that\'s always available.',
      tips: ['Gratitude is a skill you can develop', 'It shifts your perspective', 'This works by focusing on abundance'],
      encouragement: 'You\'re creating positive energy. That\'s self-care.'
    }
  ],
  'Positive Affirmations': [
    {
      instruction: 'Repeat these affirmations with conviction: "I am capable and strong." "I deserve happiness and peace." "I am growing every day." Believe in your own power.',
      tips: ['Say them like you mean them', 'Affirmations work by repetition', 'Your mind believes what you tell it'],
      encouragement: 'You\'re programming your mind for success. That\'s powerful.'
    },
    {
      instruction: 'Speak these affirmations aloud: "I am worthy of good things." "I have the strength to overcome challenges." "I am becoming better every day." Feel their truth.',
      tips: ['Use present tense', 'Believe as you speak', 'Affirmations create new neural pathways'],
      encouragement: 'You\'re building self-belief. That\'s confidence.'
    },
    {
      instruction: 'Affirm: "I am enough as I am." "I attract positive energy." "I handle challenges with grace." Repeat each one, feeling its power.',
      tips: ['Make them personal', 'Feel the emotion', 'Consistency is key'],
      encouragement: 'You\'re strengthening your self-image. That\'s growth.'
    },
    {
      instruction: 'Say with confidence: "I am resilient and strong." "I create my own happiness." "I am worthy of love and respect." These words have power.',
      tips: ['Speak with conviction', 'Visualize yourself embodying these', 'Affirmations change your self-talk'],
      encouragement: 'You\'re rewriting your inner dialogue. That\'s transformation.'
    },
    {
      instruction: 'Repeat these powerful statements: "I am capable of great things." "I choose positivity." "I am growing and improving." Let them sink in.',
      tips: ['Say them multiple times', 'Feel the truth in them', 'Your words shape your reality'],
      encouragement: 'You\'re building mental strength. That\'s empowerment.'
    }
  ],
  'Energy Movement': [
    {
      instruction: 'Stand up and stretch your arms high. Take 5 deep breaths. Do 10 gentle jumps or stretches. Feel the energy flowing through your body. Movement boosts mood naturally.',
      tips: ['Start slow and build up', 'Movement releases endorphins', 'Even small movement helps'],
      encouragement: 'You\'re activating your body\'s natural mood boosters. That\'s smart.'
    },
    {
      instruction: 'Get your body moving: Stand tall, stretch upward, breathe deeply. Do some gentle movements - jumps, stretches, or dancing. Physical activity increases happiness chemicals.',
      tips: ['Any movement counts', 'Have fun with it', 'Your body wants to move'],
      encouragement: 'You\'re boosting your energy naturally. That\'s vitality.'
    },
    {
      instruction: 'Move your body: Stretch high, take deep breaths, do 10 movements. Physical activity releases endorphins, your body\'s natural mood elevators. Feel the energy.',
      tips: ['Move in ways that feel good', 'Don\'t overthink it', 'Movement is medicine'],
      encouragement: 'You\'re creating positive energy. That\'s self-care.'
    },
    {
      instruction: 'Stand and move: Reach for the sky, breathe deeply, do some gentle exercises. Movement increases blood flow and releases feel-good chemicals. Feel the boost.',
      tips: ['Listen to your body', 'Start gentle if needed', 'Movement improves mood instantly'],
      encouragement: 'You\'re activating your natural mood boosters. That\'s wisdom.'
    },
    {
      instruction: 'Get active: Stretch, breathe, move. Do 10 simple movements. Physical activity is one of the fastest ways to improve mood. Feel the energy flowing.',
      tips: ['You don\'t need to be perfect', 'Just move', 'Your body will thank you'],
      encouragement: 'You\'re taking action to feel better. That\'s empowerment.'
    }
  ]
};

// Pre-generated Social Confidence content (5 variations per exercise)
export const SOCIAL_CONFIDENCE_CONTENT: Record<string, ExerciseContent[]> = {
  'Power Poses': [
    {
      instruction: 'Stand tall with shoulders back, hands on hips. Hold this power pose for 2 minutes. Research shows this posture increases confidence and reduces stress hormones.',
      tips: ['Your body language affects your mind', 'Stand like you\'re confident', 'This actually changes your chemistry'],
      encouragement: 'You\'re building real confidence. That\'s power.'
    },
    {
      instruction: 'Adopt a power pose: Stand with feet apart, hands on hips, chest open. Hold for 2 minutes. This posture signals confidence to your brain and body.',
      tips: ['Make yourself big', 'Breathe deeply', 'Your body creates confidence'],
      encouragement: 'You\'re programming confidence into your body. That\'s transformation.'
    },
    {
      instruction: 'Practice the power pose: Stand confidently, hands on hips, shoulders back. Hold for 2 minutes. This simple practice increases testosterone and reduces cortisol.',
      tips: ['Feel the strength in your posture', 'This is science-backed', 'Your body responds to posture'],
      encouragement: 'You\'re embodying confidence. That\'s strength.'
    },
    {
      instruction: 'Stand in a power pose: Feet apart, hands on hips, head high. Hold for 2 minutes. This posture actually changes your hormone levels, boosting confidence.',
      tips: ['Posture affects psychology', 'Stand like a leader', 'This works even if you don\'t feel confident yet'],
      encouragement: 'You\'re creating confidence from the outside in. That\'s smart.'
    },
    {
      instruction: 'Power pose: Stand tall, hands on hips, chest open. Hold for 2 minutes. Research shows this increases confidence and reduces anxiety. Your body shapes your mind.',
      tips: ['Fake it till you make it works', 'Your posture sends signals', 'This is a real technique'],
      encouragement: 'You\'re building confidence through action. That\'s empowerment.'
    }
  ],
  'Conversation Starters': [
    {
      instruction: 'Think of 3 open-ended questions you could ask someone. Practice saying them out loud. Good questions show interest and create connection. You have interesting things to share.',
      tips: ['Open-ended questions invite conversation', 'People love talking about themselves', 'Your curiosity is attractive'],
      encouragement: 'You\'re developing social skills. That\'s growth.'
    },
    {
      instruction: 'Prepare 3 conversation starters. Practice them aloud. Questions like "What brings you joy?" or "What\'s something you\'re excited about?" create meaningful connections.',
      tips: ['Ask about interests, not just facts', 'Listen more than you talk', 'Genuine interest is magnetic'],
      encouragement: 'You\'re learning to connect. That\'s skill.'
    },
    {
      instruction: 'Create 3 open-ended questions. Practice saying them. Good conversation starters are about interests, experiences, or feelings. You\'re building your social toolkit.',
      tips: ['Avoid yes/no questions', 'Show genuine curiosity', 'Your questions show you care'],
      encouragement: 'You\'re becoming more socially confident. That\'s progress.'
    },
    {
      instruction: 'Think of 3 questions that invite stories. Practice them. Questions about experiences, passions, or dreams create deeper connections. You have the ability to engage others.',
      tips: ['People remember how you made them feel', 'Good questions show intelligence', 'Your interest is a gift'],
      encouragement: 'You\'re developing connection skills. That\'s wisdom.'
    },
    {
      instruction: 'Prepare conversation starters that invite sharing. Practice 3 questions. Focus on topics that matter - interests, dreams, experiences. You\'re building social confidence.',
      tips: ['Quality over quantity', 'Be genuinely curious', 'Your questions create connection'],
      encouragement: 'You\'re learning to engage authentically. That\'s growth.'
    }
  ],
  'Self-Acceptance': [
    {
      instruction: 'List 3 things you like about yourself. Say them with conviction. You are enough. Self-acceptance is the foundation of confidence. Embrace your authentic self.',
      tips: ['You are worthy just as you are', 'Self-acceptance isn\'t arrogance', 'Your uniqueness is your strength'],
      encouragement: 'You\'re building self-love. That\'s the foundation of confidence.'
    },
    {
      instruction: 'Name 3 qualities you appreciate about yourself. Say them out loud with confidence. You are worthy of connection and friendship. Self-acceptance creates social confidence.',
      tips: ['Everyone has strengths', 'You don\'t need to be perfect', 'Self-acceptance is attractive'],
      encouragement: 'You\'re recognizing your worth. That\'s empowerment.'
    },
    {
      instruction: 'Identify 3 things you value about yourself. Express them with conviction. You are worthy of belonging. Self-acceptance allows you to show up authentically.',
      tips: ['Your worth isn\'t determined by others', 'Self-acceptance is a practice', 'You are enough right now'],
      encouragement: 'You\'re building unshakeable self-worth. That\'s strength.'
    },
    {
      instruction: 'List 3 things you\'re proud of about yourself. Say them confidently. You are worthy of connection. Self-acceptance is the key to social confidence.',
      tips: ['Focus on who you are, not what you do', 'Self-acceptance is ongoing', 'You deserve to feel good about yourself'],
      encouragement: 'You\'re cultivating self-love. That\'s transformation.'
    },
    {
      instruction: 'Name 3 things you appreciate about yourself. Say them with power. You are worthy. Self-acceptance creates the confidence to be yourself around others.',
      tips: ['Self-acceptance isn\'t selfish', 'It\'s necessary for healthy relationships', 'You are valuable'],
      encouragement: 'You\'re building authentic confidence. That\'s wisdom.'
    }
  ],
  'Visualization': [
    {
      instruction: 'Close your eyes. Picture yourself in a social situation feeling confident and at ease. See yourself engaging naturally, being yourself. Visualization prepares your mind for success.',
      tips: ['Make the visualization detailed', 'See yourself succeeding', 'Your mind can\'t tell the difference'],
      encouragement: 'You\'re programming your mind for confidence. That\'s powerful.'
    },
    {
      instruction: 'Visualize yourself in a social setting, feeling comfortable and confident. See yourself being authentic and engaging. This mental rehearsal builds real confidence.',
      tips: ['Visualization is practice', 'Your brain learns from mental rehearsal', 'See yourself succeeding'],
      encouragement: 'You\'re preparing for social success. That\'s smart.'
    },
    {
      instruction: 'Imagine yourself in a social situation, feeling confident and at ease. Picture every detail - how you stand, speak, engage. Visualization creates neural pathways for confidence.',
      tips: ['The more detailed, the better', 'Feel the confidence in your visualization', 'This is a proven technique'],
      encouragement: 'You\'re building confidence in your mind. That\'s growth.'
    },
    {
      instruction: 'Close your eyes and visualize social success. See yourself comfortable, authentic, engaging. Feel the confidence. This mental practice prepares you for real situations.',
      tips: ['Visualization is like mental practice', 'Your subconscious learns from it', 'See yourself as confident'],
      encouragement: 'You\'re creating confidence through visualization. That\'s skill.'
    },
    {
      instruction: 'Picture yourself confidently engaging in social situations. See yourself being yourself, comfortable and authentic. Visualization is a powerful confidence-building tool.',
      tips: ['Make it feel real', 'Engage all senses in visualization', 'Your mind creates what you imagine'],
      encouragement: 'You\'re programming confidence into your mind. That\'s transformation.'
    }
  ]
};

// Helper function to get random content variation
export const getRandomContent = <T extends ExerciseContent | string[]>(
  contentArray: T[]
): T => {
  return contentArray[Math.floor(Math.random() * contentArray.length)];
};

